// Code generated by protoc-gen-go.
// source: command.proto
// DO NOT EDIT!

/*
Package deploy is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	Commandconent
*/
package deploy

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type COMMAND int32

const (
	COMMAND_WHOAMI COMMAND = 0
)

var COMMAND_name = map[int32]string{
	0: "WHOAMI",
}
var COMMAND_value = map[string]int32{
	"WHOAMI": 0,
}

func (x COMMAND) Enum() *COMMAND {
	p := new(COMMAND)
	*p = x
	return p
}
func (x COMMAND) String() string {
	return proto.EnumName(COMMAND_name, int32(x))
}
func (x *COMMAND) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(COMMAND_value, data, "COMMAND")
	if err != nil {
		return err
	}
	*x = COMMAND(value)
	return nil
}

type Commandconent struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Command          *string `protobuf:"bytes,2,req,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Commandconent) Reset()         { *m = Commandconent{} }
func (m *Commandconent) String() string { return proto.CompactTextString(m) }
func (*Commandconent) ProtoMessage()    {}

func (m *Commandconent) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Commandconent) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func init() {
	proto.RegisterEnum("deploy.COMMAND", COMMAND_name, COMMAND_value)
}
